# Маршрутизация для Spring Cloud Gateway (Docker профиль)
spring:
  cloud:
    gateway:
      routes:
        # Маршрут для authentication-service
        - id: auth_route
          uri: http://authentication-service:8081
          predicates:
            - Path=/auth/**

        # Маршрут для user-service (пользователи)
        - id: user_route
          uri: http://user-service:8080
          predicates:
            - Path=/api/v1/users/**

        # Маршрут для user-service (карты)
        - id: cards_route
          uri: http://user-service:8080
          predicates:
            - Path=/api/v1/cards/**

        # Маршрут для order-service (заказы)
        - id: order_route
          uri: http://order-service:8080
          predicates:
            - Path=/api/v1/orders/**

        # Маршрут для order-service (товары)
        - id: items_route
          uri: http://order-service:8080
          predicates:
            - Path=/api/v1/items/**

